personne_index:
    path:     /
    defaults: { _controller: "CRCtpBundle:Personne:index" }
    methods:  GET

personne_show:
    path:     /{id}/show
    defaults: { _controller: "CRCtpBundle:Personne:show" }
    methods:  GET

personne_new:
    path:     /new
    defaults: { _controller: "CRCtpBundle:Personne:new" }
    methods:  [GET, POST]

personne_edit:
    path:     /{id}/edit
    defaults: { _controller: "CRCtpBundle:Personne:edit" }
    methods:  [GET, POST]

personne_delete:
    path:     /{id}/delete
    defaults: { _controller: "CRCtpBundle:Personne:delete" }
    methods:  DELETE
