<?php

namespace CRC\HelloBundle\Repository;

/**
 * TpcrcRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TpcrcRepository extends \Doctrine\ORM\EntityRepository
{
}
